### PR TITLE
Buffer.isBuffer(digest)

### PR DESCRIPTION
**Pull request by williamcotton**
Changed the conditional for ```throw new Error('digest should be a Buffer');``` to use ```Buffer.isBuffer(digest)``` instead of ```digest instanceof Buffer```.

### CODE REVIEW

**Comment by jbenet** [comment]
Ah, perfect thanks! this was before i knew `Buffer.isBuffer`

**Comment by jbenet** [comment]
someone should crawl all of npm for `instanceof Buffer` and send automatic PRs. cc @feross

**Comment by feross** [comment]
Yeah, fortunately it should be possible to subclass typed arrays soon. It's now part of the spec that arrays should be extendable. Then all `instanceof Buffer` should start working.

Node v4 is already doing that now too. So node buffer and browserify buffer are converging :+1:

**Comment by feross** [comment]
Tracking issue is here: https://github.com/feross/buffer/issues/40

**Comment by williamcotton** [comment]
Awesome! @jbenet when you get a chance can you ```npm publish``` as well? thanks!

**Comment by jbenet** [comment]
thanks! done!

**Comment by feross** [comment]
This is fixed in buffer v3.5.0 now!

https://github.com/feross/buffer/issues/40

**Pull request merged**
